package com.cmsz.sldk.model;

public class CollectState {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_state.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_state.current_num
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Integer currentNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_state.max_num
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Integer maxNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column collect_state.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Integer ghao;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_state.openid
	 * @return  the value of collect_state.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_state.openid
	 * @param openid  the value for collect_state.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_state.current_num
	 * @return  the value of collect_state.current_num
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Integer getCurrentNum() {
		return currentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_state.current_num
	 * @param currentNum  the value for collect_state.current_num
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setCurrentNum(Integer currentNum) {
		this.currentNum = currentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_state.max_num
	 * @return  the value of collect_state.max_num
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Integer getMaxNum() {
		return maxNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_state.max_num
	 * @param maxNum  the value for collect_state.max_num
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setMaxNum(Integer maxNum) {
		this.maxNum = maxNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column collect_state.ghao
	 * @return  the value of collect_state.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Integer getGhao() {
		return ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column collect_state.ghao
	 * @param ghao  the value for collect_state.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setGhao(Integer ghao) {
		this.ghao = ghao;
	}
}