package com.cmsz.sldk.model;

public class DkRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dk_record.id
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dk_record.dk_time
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private String dkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dk_record.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Integer ghao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dk_record.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private String openid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dk_record.id
	 * @return  the value of dk_record.id
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dk_record.id
	 * @param id  the value for dk_record.id
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dk_record.dk_time
	 * @return  the value of dk_record.dk_time
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public String getDkTime() {
		return dkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dk_record.dk_time
	 * @param dkTime  the value for dk_record.dk_time
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setDkTime(String dkTime) {
		this.dkTime = dkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dk_record.ghao
	 * @return  the value of dk_record.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Integer getGhao() {
		return ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dk_record.ghao
	 * @param ghao  the value for dk_record.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setGhao(Integer ghao) {
		this.ghao = ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dk_record.openid
	 * @return  the value of dk_record.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dk_record.openid
	 * @param openid  the value for dk_record.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}
}