package com.cmsz.sldk.model;

public class DkState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dk_state.current_num
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    private Integer currentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dk_state.max_num
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    private Integer maxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dk_state.ghao
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    private Integer ghao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dk_state.openid
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dk_state.current_num
     *
     * @return the value of dk_state.current_num
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public Integer getCurrentNum() {
        return currentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dk_state.current_num
     *
     * @param currentNum the value for dk_state.current_num
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public void setCurrentNum(Integer currentNum) {
        this.currentNum = currentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dk_state.max_num
     *
     * @return the value of dk_state.max_num
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public Integer getMaxNum() {
        return maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dk_state.max_num
     *
     * @param maxNum the value for dk_state.max_num
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public void setMaxNum(Integer maxNum) {
        this.maxNum = maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dk_state.ghao
     *
     * @return the value of dk_state.ghao
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public Integer getGhao() {
        return ghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dk_state.ghao
     *
     * @param ghao the value for dk_state.ghao
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public void setGhao(Integer ghao) {
        this.ghao = ghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dk_state.openid
     *
     * @return the value of dk_state.openid
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dk_state.openid
     *
     * @param openid the value for dk_state.openid
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }
}