package com.cmsz.sldk.model;

public class PzRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pz_record.id
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pz_record.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Integer ghao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pz_record.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pz_record.sendpic_time
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private String sendpicTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pz_record.latitude
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Double latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pz_record.longitude
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	private Double longitude;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pz_record.id
	 * @return  the value of pz_record.id
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pz_record.id
	 * @param id  the value for pz_record.id
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pz_record.ghao
	 * @return  the value of pz_record.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Integer getGhao() {
		return ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pz_record.ghao
	 * @param ghao  the value for pz_record.ghao
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setGhao(Integer ghao) {
		this.ghao = ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pz_record.openid
	 * @return  the value of pz_record.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pz_record.openid
	 * @param openid  the value for pz_record.openid
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pz_record.sendpic_time
	 * @return  the value of pz_record.sendpic_time
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public String getSendpicTime() {
		return sendpicTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pz_record.sendpic_time
	 * @param sendpicTime  the value for pz_record.sendpic_time
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setSendpicTime(String sendpicTime) {
		this.sendpicTime = sendpicTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pz_record.latitude
	 * @return  the value of pz_record.latitude
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Double getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pz_record.latitude
	 * @param latitude  the value for pz_record.latitude
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pz_record.longitude
	 * @return  the value of pz_record.longitude
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public Double getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pz_record.longitude
	 * @param longitude  the value for pz_record.longitude
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}
}