package com.cmsz.sldk.model;

public class YgInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_info.ygid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private Long ygid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_info.ghao
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private Integer ghao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_info.department
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_info.name
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_info.openid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private String openid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_info.ygid
	 * @return  the value of yg_info.ygid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public Long getYgid() {
		return ygid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_info.ygid
	 * @param ygid  the value for yg_info.ygid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setYgid(Long ygid) {
		this.ygid = ygid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_info.ghao
	 * @return  the value of yg_info.ghao
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public Integer getGhao() {
		return ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_info.ghao
	 * @param ghao  the value for yg_info.ghao
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setGhao(Integer ghao) {
		this.ghao = ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_info.department
	 * @return  the value of yg_info.department
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_info.department
	 * @param department  the value for yg_info.department
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_info.name
	 * @return  the value of yg_info.name
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_info.name
	 * @param name  the value for yg_info.name
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_info.openid
	 * @return  the value of yg_info.openid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_info.openid
	 * @param openid  the value for yg_info.openid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}
}