package com.cmsz.sldk.model;

public class YgMd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_md.ygid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private Long ygid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_md.ghao
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private Integer ghao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_md.name
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_md.phonenumberDh
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private String phonenumberdh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_md.phonenumber
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private String phonenumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yg_md.department
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	private String department;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_md.ygid
	 * @return  the value of yg_md.ygid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public Long getYgid() {
		return ygid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_md.ygid
	 * @param ygid  the value for yg_md.ygid
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setYgid(Long ygid) {
		this.ygid = ygid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_md.ghao
	 * @return  the value of yg_md.ghao
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public Integer getGhao() {
		return ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_md.ghao
	 * @param ghao  the value for yg_md.ghao
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setGhao(Integer ghao) {
		this.ghao = ghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_md.name
	 * @return  the value of yg_md.name
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_md.name
	 * @param name  the value for yg_md.name
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_md.phonenumberDh
	 * @return  the value of yg_md.phonenumberDh
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public String getPhonenumberdh() {
		return phonenumberdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_md.phonenumberDh
	 * @param phonenumberdh  the value for yg_md.phonenumberDh
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setPhonenumberdh(String phonenumberdh) {
		this.phonenumberdh = phonenumberdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_md.phonenumber
	 * @return  the value of yg_md.phonenumber
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public String getPhonenumber() {
		return phonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_md.phonenumber
	 * @param phonenumber  the value for yg_md.phonenumber
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yg_md.department
	 * @return  the value of yg_md.department
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yg_md.department
	 * @param department  the value for yg_md.department
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	public void setDepartment(String department) {
		this.department = department;
	}
}