package com.cmsz.sldk.mapper;

import com.cmsz.sldk.model.DkRecord;

public interface DkRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dk_record
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dk_record
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	int insert(DkRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dk_record
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	int insertSelective(DkRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dk_record
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	DkRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dk_record
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	int updateByPrimaryKeySelective(DkRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dk_record
	 * @mbg.generated  Thu Feb 08 14:37:08 CST 2018
	 */
	int updateByPrimaryKey(DkRecord record);
}