package com.cmsz.sldk.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.cmsz.sldk.model.DkState;

public interface DkStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dk_state
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    int insert(DkState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dk_state
     *
     * @mbg.generated Tue Feb 06 19:15:51 CST 2018
     */
    int insertSelective(DkState record);
    
    @Select("SELECT * FROM dk_state WHERE openid=#{openid};")
    DkState selectByOpenid(@Param("openid") String openId);
    
    @Update("UPDATE dk_state SET current_num=#{currentNum} WHERE openid=#{openid};")
    boolean updateDkState(@Param("openid") String openid, @Param("currentNum") Integer currentNum);
}