package com.cmsz.sldk.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.cmsz.sldk.model.YgInfo;

public interface YgInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yg_info
	 * @mbg.generated  Fri Feb 02 21:49:10 CST 2018
	 */
	int insert(YgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yg_info
	 * @mbg.generated  Fri Feb 02 21:49:10 CST 2018
	 */
	int insertSelective(YgInfo record);

	@Select("SELECT * FROM yg_info WHERE openid=#{openid};")
    YgInfo selectByOpenid(@Param("openid") String openId);
    
    @Select("SELECT openid FROM yg_info;")
    List<String> selectAllOpenid();
}