package com.cmsz.sldk.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.cmsz.sldk.model.YgMd;

public interface YgMdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yg_md
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	int insert(YgMd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yg_md
	 * @mbg.generated  Tue Feb 06 19:15:51 CST 2018
	 */
	int insertSelective(YgMd record);

	@Select("SELECT * FROM yg_md WHERE openid=#{openid};")
    YgMd selectByOpenid(@Param("openid") String openId);
	
	@Select("select * from yg_md where name=#{name} and ghao=#{ghao};")
	YgMd selectOne(@Param("name") String name, @Param("ghao") Integer ghao);
}