package com.cmsz.sldk.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.cmsz.sldk.model.YgMd;

public interface YgMdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yg_md
	 * @mbg.generated  Fri Feb 02 21:49:10 CST 2018
	 */
	int insert(YgMd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yg_md
	 * @mbg.generated  Fri Feb 02 21:49:10 CST 2018
	 */
	int insertSelective(YgMd record);

	@Select("SELECT * FROM yg_md WHERE openid=#{openid};")
    YgMd selectByOpenid(@Param("openid") String openId);
	
	YgMd selectOne(YgMd ygmd);
}