
server:
  port: 8080

adminPath:
  /sldk

spring:
  datasource:
#     url: jdbc:mysql://localhost:3306/sldk?useUnicode=true&characterEncoding=utf-8&useSSL=false
#     username: root
#     password: dabby@2011
     url: jdbc:mysql://192.168.41.56:3306/sldk?useUnicode=true&characterEncoding=utf-8&useSSL=false
     username: root
     password: sldk@2018
     # 使用druid数据源
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cmsz.sldk.model
  configuration:
    mapUnderscoreToCamelCase: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
        
logging:
  level:
    tk:
      mybatis: DEBUG
  config: classpath:logback-spring.xml

weixin:
  baseinfo:
     appid: wx9e13562091ff4bdb
     secret: 7fd80ef83cd2516f575321806ef83e6f
  EARTH_RADIUS: 6378.137
  GT_LATITUDE: 23.129163 #22.529550552368164 #23.129163
  GT_LONGITUDE: 113.0 #114.03778839111328  #113.0
  GT_DISTANCE: 0.050
     
